sudo: false
language: rust
rust:
- 1.21.0  # Two releases back
- stable
- beta
- nightly

matrix:
  include:
  - rust: stable
    env: RUSTFMT
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose

cache:
  cargo: true
